use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Protocol version for forward compatibility.
pub const PROTOCOL_VERSION: u32 = 1;

// --- Shell ---

/// Which shell the request originates from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
    #[serde(alias = "pwsh")]
    PowerShell,
    Nushell,
}

impl Shell {
    pub fn as_str(&self) -> &'static str {
        match self {
            Shell::Zsh => "zsh",
            Shell::Bash => "bash",
            Shell::Fish => "fish",
            Shell::PowerShell => "powershell",
            Shell::Nushell => "nushell",
        }
    }
}

// --- Request / Response ---

/// Sent by shell plugin to daemon on each keystroke (debounced).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// The full current input buffer contents.
    pub input: String,

    /// Cursor position (byte offset) within `input`.
    pub cursor: usize,

    /// Current working directory.
    pub cwd: PathBuf,

    /// Which shell is asking.
    pub shell: Shell,
}

/// Sent by daemon back to shell plugin.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// Ordered suggestions (best first). Shell plugin typically
    /// renders only the first one as ghost text.
    pub suggestions: Vec<Suggestion>,
}

// --- Suggestion ---

/// A single completion suggestion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    /// The text to insert. For full-token replacement, this is the
    /// complete replacement (e.g. "claude" when user typed "ccla").
    pub text: String,

    /// Byte offset in the original input where replacement starts.
    pub replace_start: usize,

    /// Byte offset in the original input where replacement ends.
    pub replace_end: usize,

    /// Confidence score 0.0..=1.0. Drives ghost text brightness
    /// and tier escalation decisions.
    pub confidence: f32,

    /// Which prediction tier produced this.
    pub source: SuggestionSource,

    /// Optional description (e.g. "Switch branches" for `git checkout`).
    pub description: Option<String>,
}

/// Which prediction tier produced a suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SuggestionSource {
    /// Tier 0: matched from shell history.
    History,
    /// Tier 1: matched from a CLI spec (withfig or --help parsed).
    Spec,
    /// Tier 2: generated by a local LLM.
    LocalModel,
    /// Tier 3: generated by a cloud API.
    CloudModel,
}

// --- Socket paths ---

/// Default socket path for the daemon.
pub fn default_socket_path() -> PathBuf {
    #[cfg(unix)]
    {
        let uid = unsafe { libc::getuid() };
        PathBuf::from(format!("/tmp/nighthawk-{}.sock", uid))
    }
    #[cfg(windows)]
    {
        PathBuf::from(r"\\.\pipe\nighthawk")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_roundtrip_json() {
        let req = CompletionRequest {
            input: "git ch".into(),
            cursor: 6,
            cwd: PathBuf::from("/home/user/project"),
            shell: Shell::Zsh,
        };
        let json = serde_json::to_string(&req).unwrap();
        let parsed: CompletionRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.input, "git ch");
        assert_eq!(parsed.cursor, 6);
        assert_eq!(parsed.shell, Shell::Zsh);
    }

    #[test]
    fn response_roundtrip_json() {
        let resp = CompletionResponse {
            suggestions: vec![Suggestion {
                text: "checkout".into(),
                replace_start: 4,
                replace_end: 6,
                confidence: 0.95,
                source: SuggestionSource::Spec,
                description: Some("Switch branches or restore files".into()),
            }],
        };
        let json = serde_json::to_string(&resp).unwrap();
        let parsed: CompletionResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.suggestions.len(), 1);
        assert_eq!(parsed.suggestions[0].text, "checkout");
        assert_eq!(parsed.suggestions[0].replace_start, 4);
    }

    #[test]
    fn shell_serde() {
        let s = Shell::PowerShell;
        let json = serde_json::to_string(&s).unwrap();
        assert_eq!(json, "\"powershell\"");
        let parsed: Shell = serde_json::from_str("\"pwsh\"").unwrap();
        assert_eq!(parsed, Shell::PowerShell);
    }
}
