use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Protocol version for forward compatibility.
pub const PROTOCOL_VERSION: u32 = 1;

// --- Shell ---

/// Which shell the request originates from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
    #[serde(alias = "pwsh")]
    PowerShell,
    Nushell,
}

impl Shell {
    pub fn as_str(&self) -> &'static str {
        match self {
            Shell::Zsh => "zsh",
            Shell::Bash => "bash",
            Shell::Fish => "fish",
            Shell::PowerShell => "powershell",
            Shell::Nushell => "nushell",
        }
    }
}

// --- Request / Response ---

/// Sent by shell plugin to daemon on each keystroke (debounced).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionRequest {
    /// The full current input buffer contents.
    pub input: String,

    /// Cursor position (byte offset) within `input`.
    pub cursor: usize,

    /// Current working directory.
    pub cwd: PathBuf,

    /// Which shell is asking.
    pub shell: Shell,
}

/// Sent by daemon back to shell plugin.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// Ordered suggestions (best first). Shell plugin typically
    /// renders only the first one as ghost text.
    pub suggestions: Vec<Suggestion>,
}

// --- Suggestion ---

/// A single completion suggestion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    /// The text to insert. For full-token replacement, this is the
    /// complete replacement (e.g. "claude" when user typed "ccla").
    pub text: String,

    /// Byte offset in the original input where replacement starts.
    pub replace_start: usize,

    /// Byte offset in the original input where replacement ends.
    pub replace_end: usize,

    /// Confidence score 0.0..=1.0. Drives ghost text brightness
    /// and tier escalation decisions.
    pub confidence: f32,

    /// Which prediction tier produced this.
    pub source: SuggestionSource,

    /// Optional description (e.g. "Switch branches" for `git checkout`).
    pub description: Option<String>,

    /// Character-level diff ops for inline diff rendering of fuzzy matches.
    /// None for prefix matches (use normal ghost text). Some for fuzzy matches.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diff_ops: Option<Vec<DiffOp>>,
}

/// A single character-level diff operation for inline rendering.
///
/// Fuzzy matches produce a sequence of these ops describing how the
/// typed text differs from the corrected text. The shell plugin uses
/// them to render strikethrough (Delete), gray ghost (Insert), and
/// normal (Keep) characters inline.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "op", content = "ch")]
pub enum DiffOp {
    /// Character matches — render in normal color.
    Keep(char),
    /// Character should be removed — render as strikethrough red.
    Delete(char),
    /// Character should be inserted — render as gray ghost text.
    Insert(char),
}

/// Which prediction tier produced a suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SuggestionSource {
    /// Tier 0: matched from shell history.
    History,
    /// Tier 1: matched from a CLI spec (withfig or --help parsed).
    Spec,
    /// Tier 2: generated by a local LLM.
    LocalModel,
    /// Tier 3: generated by a cloud API.
    CloudModel,
}

// --- Socket paths ---

/// Default socket path for the daemon.
pub fn default_socket_path() -> PathBuf {
    #[cfg(unix)]
    {
        let uid = unsafe { libc::getuid() };
        PathBuf::from(format!("/tmp/nighthawk-{}.sock", uid))
    }
    #[cfg(windows)]
    {
        PathBuf::from(r"\\.\pipe\nighthawk")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_roundtrip_json() {
        let req = CompletionRequest {
            input: "git ch".into(),
            cursor: 6,
            cwd: PathBuf::from("/home/user/project"),
            shell: Shell::Zsh,
        };
        let json = serde_json::to_string(&req).unwrap();
        let parsed: CompletionRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.input, "git ch");
        assert_eq!(parsed.cursor, 6);
        assert_eq!(parsed.shell, Shell::Zsh);
    }

    #[test]
    fn response_roundtrip_json() {
        let resp = CompletionResponse {
            suggestions: vec![Suggestion {
                text: "checkout".into(),
                replace_start: 4,
                replace_end: 6,
                confidence: 0.95,
                source: SuggestionSource::Spec,
                description: Some("Switch branches or restore files".into()),
                diff_ops: None,
            }],
        };
        let json = serde_json::to_string(&resp).unwrap();
        let parsed: CompletionResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.suggestions.len(), 1);
        assert_eq!(parsed.suggestions[0].text, "checkout");
        assert_eq!(parsed.suggestions[0].replace_start, 4);
    }

    #[test]
    fn shell_serde() {
        let s = Shell::PowerShell;
        let json = serde_json::to_string(&s).unwrap();
        assert_eq!(json, "\"powershell\"");
        let parsed: Shell = serde_json::from_str("\"pwsh\"").unwrap();
        assert_eq!(parsed, Shell::PowerShell);
    }

    #[test]
    fn diff_op_roundtrip() {
        let ops = vec![
            DiffOp::Keep('c'),
            DiffOp::Delete('a'),
            DiffOp::Insert('e'),
            DiffOp::Keep('k'),
        ];
        let json = serde_json::to_string(&ops).unwrap();
        let parsed: Vec<DiffOp> = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, ops);
    }

    #[test]
    fn suggestion_with_diff_ops() {
        let suggestion = Suggestion {
            text: "checkout".into(),
            replace_start: 4,
            replace_end: 12,
            confidence: 0.7,
            source: SuggestionSource::Spec,
            description: None,
            diff_ops: Some(vec![DiffOp::Keep('c'), DiffOp::Insert('h')]),
        };
        let json = serde_json::to_string(&suggestion).unwrap();
        assert!(json.contains("diff_ops"));
        let parsed: Suggestion = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.diff_ops.unwrap().len(), 2);
    }

    #[test]
    fn suggestion_without_diff_ops_backward_compat() {
        // Old JSON without diff_ops field should deserialize with None
        let json = r#"{"text":"checkout","replace_start":4,"replace_end":6,"confidence":0.9,"source":"spec","description":null}"#;
        let parsed: Suggestion = serde_json::from_str(json).unwrap();
        assert!(parsed.diff_ops.is_none());
    }

    #[test]
    fn powershell_request_with_windows_path() {
        // Simulates the JSON the PowerShell plugin sends (backslashes escaped)
        let json = r#"{"input":"cd C:\\Users\\iamsu","cursor":18,"cwd":"D:\\projects\\nighthawk","shell":"powershell"}"#;
        let parsed: CompletionRequest = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.input, r"cd C:\Users\iamsu");
        assert_eq!(parsed.cursor, 18);
        assert_eq!(parsed.cwd, PathBuf::from(r"D:\projects\nighthawk"));
        assert_eq!(parsed.shell, Shell::PowerShell);
    }

    #[test]
    fn powershell_request_with_quotes_in_input() {
        // Input containing escaped double quotes
        let json = r#"{"input":"echo \"hello world\"","cursor":20,"cwd":"C:\\","shell":"pwsh"}"#;
        let parsed: CompletionRequest = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.input, r#"echo "hello world""#);
        assert_eq!(parsed.shell, Shell::PowerShell); // pwsh alias
    }

    #[test]
    fn powershell_request_unc_path() {
        let json = r#"{"input":"dir","cursor":3,"cwd":"\\\\server\\share","shell":"powershell"}"#;
        let parsed: CompletionRequest = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.cwd, PathBuf::from(r"\\server\share"));
    }

    #[test]
    fn suggestion_none_diff_ops_omitted_in_json() {
        // diff_ops: None should not appear in serialized JSON (skip_serializing_if)
        let suggestion = Suggestion {
            text: "checkout".into(),
            replace_start: 4,
            replace_end: 6,
            confidence: 0.9,
            source: SuggestionSource::Spec,
            description: None,
            diff_ops: None,
        };
        let json = serde_json::to_string(&suggestion).unwrap();
        assert!(
            !json.contains("diff_ops"),
            "None diff_ops should be omitted: {}",
            json
        );
    }
}
